import { Types } from '../../../../interactive-maps'
/**
 * TODO: We need to ask how to handle the Categories with Promotion in areas.
 * Because right now, we are creating special category like PROMOTION. So
 * I've been thinking that promotion areas are special. This will affect the
 * categories assign to some promotion areas.
 * TODO: We need to ask the areas without categories to Kamil
 *
 * What we need to do is our interactive maps should not be aware about the Store areas.
 * Yes, it will be awared on the svg but Store areas will not. Interactive maps should
 * expose an api like wayfinder which will accept the areas type of the UpdatedProduct.
 * StoreAreas will hold all the store areas on the store. Merge all the areas with their
 * corresponding floor.
 *
 */

const storeAreas: Types.StoreAreas = {
  // Level Two floor
  // Level Two floor
  // Level Two floor
  // Level Two floor
  'point-of-sale': {
    id: 'point-of-sale',
    label: 'Point of Sale',
    type: 'store',
    nodes: ['node_0.140509'],
    categories: [],
    floorID: 'levelOneFloor',
  },
  woc: {
    id: 'woc',
    label: 'WOC',
    type: 'store',
    nodes: ['node_0.954616'],
    categories: [],
    floorID: 'levelOneFloor',
  },
  souvenirs: {
    id: 'souvenirs',
    label: 'Souvenirs',
    type: 'store',
    nodes: ['node_0.997918'],
    categories: ['DCIS_0910011', 'DCIS_092'],
    floorID: 'levelOneFloor',
  },
  contentainment: {
    id: 'contentainment',
    label: 'Contentainment',
    type: 'store',
    nodes: ['node_0.586891'],
    categories: [],
    floorID: 'levelOneFloor',
  },
  toys: {
    id: 'toys',
    label: 'Toys',
    type: 'store',
    nodes: ['node_0.795777'],
    categories: [
      'DCIS_092002',
      'DCIS_060',
      'DCIS_060003',
      'DCIS_0600031',
      'DCIS_0600032',
    ],
    floorID: 'levelOneFloor',
  },
  cigarettes: {
    id: 'cigarettes',
    label: 'Cigarettes',
    type: 'store',
    nodes: ['node_0.711'],
    categories: ['DCIS_010001', 'DCIS_01000116', 'DCIS_010007'],
    floorID: 'levelOneFloor',
  },
  tobacco: {
    id: 'tobacco',
    label: 'Tobacco',
    type: 'store',
    nodes: ['node_0.08419'],
    categories: ['DCIS_010004', 'DCIS_0100042', 'DCIS_010005', ''],
    floorID: 'levelOneFloor',
  },
  'perfumes-and-cosmetics-promotion': {
    id: 'perfumes-and-cosmetics-promotion',
    label: 'Perfumes and Cosmetics Promotion',
    type: 'store',
    nodes: ['node_0.541345'],
    categories: ['DCIS_040005'],
    floorID: 'levelOneFloor',
  },
  'liquor-promotion': {
    id: 'liquor-promotion',
    label: 'Liquor Promotion',
    type: 'store',
    nodes: ['node_0.17108'],
    categories: [''],
    floorID: 'levelOneFloor',
  },
  liquor: {
    id: 'liquor',
    label: 'Liquor',
    type: 'store',
    nodes: ['node_0.97985', 'node_0.17108'],
    categories: ['DCIS_0200052', 'DCIS_020005'],
    floorID: 'levelOneFloor',
  },
  'alcoholic-beverages-promotion': {
    id: 'alcoholic-beverages-promotion',
    label: 'Alcoholic Beverages Promotion',
    type: 'store',
    nodes: ['node_0.864615'],
    categories: ['DCIS_020009'],
    floorID: 'levelOneFloor',
  },
  'alcoholic-beverages': {
    id: 'alcoholic-beverages',
    label: 'Alcoholic Beverages',
    type: 'store',
    nodes: ['node_0.932309'],
    categories: ['DCIS_0200091', 'DCIS_0200092', 'DCIS_020009'],
    floorID: 'levelOneFloor',
  },
  'gift-boxes': {
    id: 'gift-boxes',
    label: 'Gift Boxes',
    type: 'store',
    nodes: ['node_0.925193'],
    categories: [
      'DCIS_0500091',
      'DCIS_0700023',
      'DCIS_090005',
      'DCIS_09000517',
      'DCIS_09000517',
      'DCIS_09000518',
      'DCIS_09000519',
      'DCIS_0900059',
    ],
    floorID: 'levelOneFloor',
  },
  // TODO: We need to ask this area because right now its category
  // is not handled by our provider due to its category syntax.
  'madrid-t1-nsh-perfumeria': {
    id: 'madrid-t1-nsh-perfumeria',
    label: 'Madrid Perfume',
    type: 'store',
    nodes: ['node_0.102676'],
    categories: [],
    floorID: 'levelOneFloor',
  },
  sunglasses: {
    id: 'sunglasses',
    label: 'Sunglasses',
    type: 'store',
    nodes: ['node_0.147593'],
    categories: [
      'DCIS_01000516',
      'DCIS_050006',
      'DCIS_0500061',
      'DCIS_07000516',
    ],
    floorID: 'levelOneFloor',
  },
  'fashion-and-luxury': {
    id: 'fashion-and-luxury',
    label: 'Fashion and Luxury',
    type: 'store',
    nodes: ['node_0.091099'],
    categories: ['DCIS_050'],
    floorID: 'levelOneFloor',
  },
  // Basement
  // Basement
  // Basement
  // Basement
  'mens-plus-sizes': {
    id: 'mens-plus-sizes',
    label: 'Mens Plus Sizes',
    type: 'store',
    nodes: ['node_0.0806'],
    categories: ['DCIS_050'],
    floorID: 'basementFloor',
  },
  'mens-sleepwear': {
    id: 'mens-sleepwear',
    label: 'Mens Sleepwear',
    type: 'store',
    nodes: ['node_0.5324'],
    categories: ['DCIS_050'],
    floorID: 'basementFloor',
  },
  'mens-workwear': {
    id: 'mens-workwear',
    label: 'Mens Workwear',
    type: 'store',
    nodes: ['node_0.2787'],
    categories: ['DCIS_050'],
    floorID: 'basementFloor',
  },
  'mens-footwear': {
    id: 'mens-footwear',
    label: 'Mens Footwear',
    type: 'store',
    nodes: ['node_0.7839'],
    categories: ['node_0.2787'],
    floorID: 'basementFloor',
  },
  'mens-accessories': {
    id: 'mens-accessories',
    label: 'Mens Accessories',
    type: 'store',
    nodes: ['node_0.8324'],
    categories: ['DCIS_050'],
    floorID: 'basementFloor',
  },
  'mens-businesswear': {
    id: 'mens-businesswear',
    label: 'Mens Businesswear',
    type: 'store',
    nodes: ['node_0.9783'],
    categories: ['DCIS_050'],
    floorID: 'basementFloor',
  },
  'mens-top-bottom': {
    id: 'mens-top-bottom',
    label: 'Mens Tops and Bottoms',
    type: 'store',
    nodes: ['node_mens-top-bottom'],
    categories: ['DCIS_050'],
    floorID: 'basementFloor',
  },
  'fitting-room-extra': {
    id: 'fitting-room-extra',
    label: 'Fitting Room Extra',
    type: 'store',
    nodes: ['node_0.135'],
    categories: ['DCIS_050'],
    floorID: 'basementFloor',
  },
  'mens-socks': {
    id: 'mens-socks',
    label: 'Mens Sock',
    type: 'store',
    nodes: ['node_0.272751'],
    categories: ['DCIS_050'],
    floorID: 'basementFloor',
  },
  'mens-brands': {
    id: 'mens-brands',
    label: 'Mens Brands',
    type: 'store',
    nodes: ['node_0.0859'],
    categories: ['DCIS_050'],
    floorID: 'basementFloor',
  },
  'mens-active': {
    id: 'mens-active',
    label: 'Mens Active Wear',
    type: 'store',
    nodes: ['node_0.4003'],
    categories: ['DCIS_050'],
    floorID: 'basementFloor',
  },
  'fitting-room': {
    id: 'fitting-room',
    label: 'Fitting Room',
    type: 'store',
    nodes: ['node_0.8493324'],
    categories: ['DCIS_050'],
    floorID: 'basementFloor',
  },
  // Ground floor
  // Ground floor
  // Ground floor
  // Ground floor
  'womens-casual-bottoms': {
    id: 'womens-casual-bottoms',
    label: 'Womens Casual Bottoms',
    type: 'store',
    nodes: ['node_0.6743'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'womens-casual-tops': {
    id: 'womens-casual-tops',
    label: 'Womens Casual Tops',
    type: 'store',
    nodes: ['node_0.2241'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'womens-shoes': {
    id: 'womens-shoes',
    label: 'Womens Shoes',
    type: 'store',
    nodes: ['node_0.8728'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  cosmetics: {
    id: 'cosmetics',
    label: 'Cosmetics',
    type: 'store',
    nodes: ['node_0.1019'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'personal-care': {
    id: 'personal-care',
    label: 'Personal Care',
    type: 'store',
    nodes: ['node_0.7976'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'piping-hot': {
    id: 'piping-hot',
    label: 'Piping Hot',
    type: 'store',
    nodes: ['node_0.752'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'city-dressing': {
    id: 'city-dressing',
    label: 'City Dressing',
    type: 'store',
    nodes: ['node_0.2656'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  maternity: {
    id: 'maternity',
    label: 'Maternity',
    type: 'store',
    nodes: ['node_0.1523'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'ladies-fashion-accessories': {
    id: 'ladies-fashion-accessories',
    label: 'Ladies Fashion Accessories',
    type: 'store',
    nodes: ['node_0.6308'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'ladies-nightwear': {
    id: 'ladies-nightwear',
    label: 'Ladies Nightwear',
    type: 'store',
    nodes: ['node_0.6493'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  bras: {
    id: 'bras',
    label: 'Bras',
    type: 'store',
    nodes: ['node_0.1236'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'ladies-swimwear': {
    id: 'ladies-swimwear',
    label: 'Ladies Swimwear',
    type: 'store',
    nodes: ['node_0.2561'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'lingerie-co-ordinates': {
    id: 'lingerie-co-ordinates',
    label: 'Lingerie',
    type: 'store',
    nodes: ['node_0.2385'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'ladies-briefs': {
    id: 'ladies-briefs',
    label: 'Ladies Briefs',
    type: 'store',
    nodes: ['node_0.2256'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'ladies-hoisery': {
    id: 'ladies-hoisery',
    label: 'Ladies Hoisery',
    type: 'store',
    nodes: ['node_0.9732'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  toiletries: {
    id: 'toiletries',
    label: 'Toiletries',
    type: 'store',
    nodes: ['node_0.7293'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'books-1': {
    id: 'books-1',
    label: 'Books- 1',
    type: 'store',
    nodes: ['node_0.4726'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'everyday-confectionary': {
    id: 'everyday-confectionary',
    label: 'Everyday Confectionary',
    type: 'store',
    nodes: ['node_0.8179'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'dresses-soft-seperates': {
    id: 'dresses-soft-seperates',
    label: 'Dressess Soft Separates',
    type: 'store',
    nodes: ['node_0.5542'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'womens-activewear': {
    id: 'womens-activewear',
    label: 'Womens Activewear',
    type: 'store',
    nodes: ['node_0.4826'],
    categories: ['DCIS_050'],
    floorID: 'groundFloor',
  },
  'elevator-1': {
    id: 'elevator-1',
    label: 'Elevator 1',
    type: 'portal',
    nodes: ['node_elevator-1'],
    floorID: '',
  },
  'escalator-basement': {
    id: 'escalator-basement',
    label: 'Escalator (to Basement)',
    type: 'portal',
    nodes: ['node_escalator-to-basement'],
    floorID: '',
  },
  'escalator-1-ground-level': {
    id: 'escalator-1-ground-level',
    label: 'Escalator 1 (to Ground Level)',
    type: 'portal',
    nodes: ['node_escalator-to-ground-level'],
    floorID: '',
  },
}

export default storeAreas
